CREATE TABLE Author
(
Id integer PRIMARY KEY AUTO_INCREMENT,
Name nvarchar(100) NOT NULL UNIQUE
);

CREATE TABLE Book
(
Id integer PRIMARY KEY AUTO_INCREMENT,
Title NVARCHAR(300) NOT NULL,
ISBNumber NVARCHAR(13) NOT NULL UNIQUE,
Publication_Year INTEGER,
Pages_Number INTEGER,
Author_Id INTEGER,
FOREIGN KEY(Author_Id) REFERENCES Author(Id) ON DELETE CASCADE
);
